### ISSUE TITLE
<noscript><meta http-equiv="refresh" content="..."></noscript> truncates URL if it contains U+0027 (')

### ISSUE THREAD

**Issue by whiteroses** [uBlockOrigin/uMatrix-issues#222]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

With script disabled, uMatrix truncates the URL in `<noscript><meta http-equiv="refresh" content="..."></noscript>` if it contains U+0027 (`'`).  

### A specific URL where the issue occurs

(The "Steps to Reproduce" below makes the issue much clearer (and shows that it's not an issue with Twitter), but Twitter was where I first found the issue, so this may be helpful as an alternative demo.)

https://twitter.com/bbtester7777/status/1226554296302546944

With the rule of `* 1st-party * allow` that comes with a default uMatrix installation, if we click on the link to `https://example.com/foo'bar`, we are taken to https://example.com/foo'bar as expected; but if we temporarily remove the `* 1st-party * allow` rule and click the link again, we are now taken to https://example.com/foo instead.

### Steps to Reproduce

1. Create the following HTML file:
```html
<!DOCTYPE html>
<html>
        <head> 
                <meta charset="UTF-8">
                <noscript>
                        <meta http-equiv="refresh" content="0;URL=http://example.com/foo'bar">
                </noscript>
        </head>
        <body>
        </body>
</html>
```
2. Serve it locally (e.g. with `python3 -m http.server --bind 127.0.0.1`) and load page in browser. As uMatrix's default installation sets the `* 1st-party * allow` rule by default, the page is blank.
3. Disable script for 127.0.0.1, and reload page. This takes us to https://example.com/foo, with the URL truncated.

### Ruleset

Default installation, with script disabled as described above.

### Supporting evidence

I don't think there's any supporting evidence that would make the issue clearer, but please let me know if there's any further information I can provide that would be helpful.

### Your environment

* uMatrix version: uMatrix 1.4.0 and uMatrix development build 1.4.1.0
* Browser Name and version: Tested in Chrome 79.0.3945.130 (Official Build) (64-bit) and Firefox Extended Support Release 68.4.1esr (64-bit)
* Operating System and version: Debian GNU/Linux 10 (buster)

I think the issue is the regular expression at https://github.com/gorhill/uMatrix/blob/master/src/js/contentscript.js#L477: replacing `[^'"]` with `[^\2]` fixes the issue. (U+0027 (`'`) is a valid character in the path, but U+0022 (`"`) is not (according to https://url.spec.whatwg.org/#url-path-segment-string); however [the algorithm in the spec](https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-refresh) seems to accept both, and this change is in line with that algorithm.) If you agree with this change, I'd be happy to submit a PR if that would be helpful. Thanks!

**Comment by whiteroses** [comment]
(Edited comment to mention truncation for `"` in addition to `'`, as well as the character references representing the two characters; and better explain the suggested fix.)

**Comment by gwarser** [comment]
Did you check the case without quotation marks?

**Comment by whiteroses** [comment]
Yes: umatrix currently truncates at first encounter of `'`, `"`, or their character references; browsers and suggested fix do not truncate, but percent-encode `"`s and its character references.

**Comment by whiteroses** [comment]
(Edited first comment: to correct parts where I'd got confused between the quotes around the URL and the quotes around the attribute value &mdash; though this does not change the truncation issue or the suggested fix; mention differences between the standards and between the standard and the browser that I've run into, that may be relevant; and include code examples of directly using the regex.)
